[project]
name = "delay_predictor"
authors = [
    { name = "gangadhar kadam", email = "email.kadam@gmail.com"}
]
description = "Frappe/ERPNext app designed to enhance the Manufacturing Module with intelligent delay prediction.It uses machine learning models and business rules to analyze factors like raw material availability, machine downtime, and workforce capacity."
requires-python = ">=3.10"
readme = "README.md"
dynamic = ["version"]
dependencies = [
    # "frappe~=15.0.0" # Installed and managed by bench.
]

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

# These dependencies are only installed when developer mode is enabled
[tool.bench.dev-dependencies]
# package_name = "~=1.1.0"
